"""Build static journal pages and homepage metadata from posts/*.md."""
import html
import json
import re
from datetime import date
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- Generated by scripts/build_notes.py -->"


def read_post(path):
    text = path.read_text(encoding="utf-8-sig")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", text, re.S)
    if not match:
        raise ValueError(f"{path.name}: missing metadata block")
    fields = {}
    for line in match[1].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, value = line.partition(":")
        if not separator or key.strip() not in {"title", "date", "summary", "draft"}:
            raise ValueError(f"{path.name}: invalid metadata line: {line}")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fields[key.strip()] = value
    if fields.get("draft", "true").lower() not in {"true", "false"}:
        raise ValueError(f"{path.name}: draft must be true or false")
    if fields.get("draft", "true").lower() == "true":
        return None
    for key in ["title", "date", "summary"]:
        if not fields.get(key):
            raise ValueError(f"{path.name}: missing {key}")
    date.fromisoformat(fields["date"])
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", path.stem):
        raise ValueError(f"{path.name}: use lowercase letters, numbers and hyphens for the filename")
    return {**fields, "slug": path.stem, "body": match[2]}


def render(post):
    title = html.escape(post["title"])
    summary = html.escape(post["summary"], quote=True)
    body = markdown.markdown(post["body"], extensions=["fenced_code", "tables", "sane_lists"])
    return f'''{GENERATED}
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} | Yichen's notes</title><meta name="description" content="{summary}">
<link rel="icon" href="../../assets/favicon.svg"><link rel="stylesheet" href="../../assets/style.css"><link rel="stylesheet" href="../../assets/notes.css"></head>
<body><div class="site-shell"><header class="masthead"><a class="wordmark" href="../../">yichen<span>.space</span></a><span>Notes from my desk</span></header>
<nav class="navigation" aria-label="Main navigation"><a href="../../#journal">← All notes</a><a href="../../">Home</a></nav>
<main class="note-page"><header class="note-header"><p class="note-kicker">FROM THE JOURNAL</p><h1>{title}</h1><p><time datetime="{post['date']}">{post['date']}</time> · Yichen Feng</p></header><article class="note-body">{body}</article><a class="note-back" href="../../#journal">← Back to all notes</a></main>
<footer><span>Yichen Feng · Personal notes</span><a href="../../credits.html">Colophon &amp; credits</a></footer></div></body></html>
'''


def build(root=ROOT):
    # Validate and render everything before replacing any existing output.
    posts = []
    for path in sorted((root / "posts").glob("*.md")):
        if path.name.startswith("_") or path.name.lower() == "readme.md":
            continue
        post = read_post(path)
        if post:
            posts.append(post)
    posts.sort(key=lambda post: (post["date"], post["slug"]), reverse=True)
    rendered = [(post, render(post)) for post in posts]
    output = root / "notes"
    output.mkdir(exist_ok=True)
    wanted = {post["slug"] for post in posts}
    for page in output.glob("*/index.html"):
        if page.parent.name not in wanted and page.read_text(encoding="utf-8").startswith(GENERATED):
            page.unlink()  # Only generated files directly under the intended notes directory.
            if not any(page.parent.iterdir()):
                page.parent.rmdir()
    for post, content in rendered:
        directory = output / post["slug"]
        directory.mkdir(exist_ok=True)
        (directory / "index.html").write_text(content, encoding="utf-8")
    metadata = [{"title": post["title"], "date": post["date"], "summary": post["summary"], "url": f"notes/{post['slug']}/"} for post in posts]
    (root / "data").mkdir(exist_ok=True)
    (root / "data" / "notes.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Built {len(posts)} published note(s).")


if __name__ == "__main__":
    build()
